version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: crowdfunding-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Asdfg12345@
      MYSQL_DATABASE: Crowdfunding
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  crowdfunding-app:
    image: crowdfunding-app
    container_name: crowdfunding-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Crowdfunding
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Asdfg12345@
    ports:
      - "8080:8080"

volumes:
  mysql_data:
